services:
  - type: web
    name: healthhub
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: healthhubdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: healthhubdb